# Football API
football.api.key=8bc58981ec4e484f8fbcaaa80eed3e6e
ch.elio.football.FootballClient/mp-rest/url=https://api.football-data.org

# Quarkus Cache
quarkus.cache.caffeine.standings-cache.expire-after-write=5M
quarkus.cache.caffeine.scorers-cache.expire-after-write=10M
quarkus.cache.caffeine.matchday-cache.expire-after-write=5M